Institution.create(name: "Vox Populi")
Institution.create(name: "ICA Philadelphia")
Institution.create(name: "Fabric Workshop & Museum")
Institution.create(name: "Mutter Museum")
Institution.create(name: "PMA")
Institution.create(name: "Field Museum")
Institution.create(name: "MCA Chicago")
Institution.create(name: "Icebox Project Space")

Artist.create(name: "NIC Kay", email: "studio@nic-kay.com")
Artist.create(name: "Steven Reker", email: "stevenreker@gmail.com")
Artist.create(name: "Dylan Wright", email: "dylanmatracia@gmail.com")
Artist.create(name: "Stephanie Acosta", email: "wakingstephanie@gmail.com")
Artist.create(name: "Zach Hill", email: "zachjoehill@gmail.com")
Artist.create(name: "Moon Baby", email: "samejamesperry@gmail.com")
Artist.create(name: "Lane Speidel", email: "lane_ruuls@gmail.com")
Artist.create(name: "Katie Rauth", email: "katie_ruuls@gmail.com")
Artist.create(name: "Marion", email: "marions_puppetss@gmail.com")
Artist.create(name: "Dan Foley", email: "dan@dan-foley.com")
